<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bfbn"
 *
 * Auto generated by Extension Builder 2020-02-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'BFBN',
    'description' => 'MB-Dienststellen - Schulen',
    'category' => 'plugin',
    'author' => 'BFBN-Team',
    'author_email' => 'info@bfbn.de',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.0.0-11.99.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
