imports:
  - { resource: Backend/DashboardWidgets.yaml }
  
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MbFosbos\Bfbn\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
    
  MbFosbos\Bfbn\Utility\FormHook:
    public: true
    
  MbFosbos\Bfbn\EventListener\LoginBeforeRedirectEvent:
    tags:
      - name: event.listener
        identifier: 'myLoginBeforeRedirectEvent'    
